// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarframeUtil.Data;

#nullable disable

namespace WarframeUtil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WarframeUtil.Data.DbDate", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RivenDBClassId")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.HasIndex("RivenDBClassId");

                    b.ToTable("DbDate");
                });

            modelBuilder.Entity("WarframeUtil.Data.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RivenDBClassId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("PriceId");

                    b.HasIndex("RivenDBClassId");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("WarframeUtil.Data.PriceAvg", b =>
                {
                    b.Property<int>("PriceAvgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RivenDBClassId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("PriceAvgId");

                    b.HasIndex("RivenDBClassId");

                    b.ToTable("PriceAvg");
                });

            modelBuilder.Entity("WarframeUtil.Data.RivenDBClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Rivens");
                });

            modelBuilder.Entity("WarframeUtil.Data.UnrolledAvg", b =>
                {
                    b.Property<int>("UnrolledAvgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RivenDBClassId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("UnrolledAvgId");

                    b.HasIndex("RivenDBClassId");

                    b.ToTable("UnrolledAvg");
                });

            modelBuilder.Entity("WarframeUtil.Data.DbDate", b =>
                {
                    b.HasOne("WarframeUtil.Data.RivenDBClass", "RivenDbClass")
                        .WithMany("DDate")
                        .HasForeignKey("RivenDBClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RivenDbClass");
                });

            modelBuilder.Entity("WarframeUtil.Data.Price", b =>
                {
                    b.HasOne("WarframeUtil.Data.RivenDBClass", "RivenDbClass")
                        .WithMany("Prices")
                        .HasForeignKey("RivenDBClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RivenDbClass");
                });

            modelBuilder.Entity("WarframeUtil.Data.PriceAvg", b =>
                {
                    b.HasOne("WarframeUtil.Data.RivenDBClass", "RivenDbClass")
                        .WithMany("PriceAvg")
                        .HasForeignKey("RivenDBClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RivenDbClass");
                });

            modelBuilder.Entity("WarframeUtil.Data.UnrolledAvg", b =>
                {
                    b.HasOne("WarframeUtil.Data.RivenDBClass", "RivenDbClass")
                        .WithMany("UnrolledAvg")
                        .HasForeignKey("RivenDBClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RivenDbClass");
                });

            modelBuilder.Entity("WarframeUtil.Data.RivenDBClass", b =>
                {
                    b.Navigation("DDate");

                    b.Navigation("PriceAvg");

                    b.Navigation("Prices");

                    b.Navigation("UnrolledAvg");
                });
#pragma warning restore 612, 618
        }
    }
}
